name: Package and Release Addon

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Package SteamDeckElvUIInstaller
        run: |
          cd SteamDeckElvUIInstaller
          zip -r ../SteamDeckElvUIInstaller.zip ./*
          cd ..

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: SteamDeckElvUIInstaller.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
